### PR TITLE
fix: block requests to probe IPs

### LINKED ISSUE #346: globalping-probe leaks host's services and host's local network when containerized
Since the container runs with `--net=host`, it naturally leaks the host's whole network, and combined with globalping providing HTTP(S) requests, it has huge potential for Remote Code Execution and sensitive data exfiltration.

Consider the following hypothetically:
 
- Alongsize containerized `globalping-probe`, host runs a certain file sync service, which exposes a web interface
- The web interface:
  - Is exposed through a well-known port
  - Allows for setting up additional machines for syncing
  - The web interface has no authentication method set by default

The attacker would:

- Send a request to a server controlled by them, exposing the host's public IP address
- Send an http request via the host (from globalping.io), to its public address at the vulnerable port
- Host's kernel is smart enough that it routes requests its own external IP internally, to 127.0.0.1
- They now set up a machine under their control for syncing via the web interface

The solution found by me was:

1. Create a separate user and configure it for rootless podman
2. On firewall, using the owner module, reject packets where 'owner' is this new uid and dest addr is:
   - for v4 `127.0.0.0/8` and other CIDRs that are routed via local machine or local network, e.g. `192.0.0.0/24` and `10.0.0.0/8` etc
   - for v6 `::1/128`, `fe80::/10`, `fc00::/7`, `ff00::/8` and CIDR for globally routable IPv6 addr, e.g. `1234:5678:90ab:cdef::/64`
3. Set custom DNS resolvers for the container (e.g. `1.1.1.1`, `8.8.8.8`), otherwise it would break DNS resolution inside the container
4. Start the container, rootless, from this new user

It seems to me `globalping-probe` should filter out those addresses internally. That would be nice. =)

### PR DESCRIPTION
**Pull request by alexey-yarmosh**
Fixes https://github.com/jsdelivr/globalping-probe/issues/346

### CODE REVIEW

**Review by MartinKolarik — CHANGES_REQUESTED** [review]
This is way too complicated and still not fully reliable since it relies on API responses to collect the IPs.

Instead, factor out [this](https://github.com/jsdelivr/globalping-probe/blob/f4dfbf2ef73c9d643b57c6fa234c00254cc55eb9/src/helper/alt-ips-client.ts#L64-L72) and do the blocking based on local addresses. We don't need to verify if they are truly public for this. Also, instead of custom logic for HTTP, we should include this in the existing private IP check.

**Comment by MartinKolarik** [comment]
> Instead, factor out [this](https://github.com/jsdelivr/globalping-probe/blob/f4dfbf2ef73c9d643b57c6fa234c00254cc55eb9/src/helper/alt-ips-client.ts#L64-L72)

Actually, @PavelKopecky did exactly that in https://github.com/jsdelivr/globalping-probe/pull/345/changes#diff-7b263f3f959c0cfe5c6c4d3a66923bfe9c860d7938af1504123f0db836408780 so let's reuse that.

**Review by MartinKolarik — APPROVED** [review]

File: src/lib/private-ip.ts [hunk 1]
```diff
@@ -53,12 +62,32 @@ export const isIpPrivate = (ip: string) => {
...
+	}
+
+	localIps = new Set(_(os.networkInterfaces())
+		.values()
+		.filter(is.truthy)
+		.flatten()
+		.uniqBy('address')
+		.filter(address => !address.internal)
+		.filter(address => !address.address.startsWith('fe80:')) // filter out link-local addresses
+		.filter(address => !address.address.startsWith('FE80:')) // filter out link-local addresses
```
Comment (MartinKolarik) [inline src/lib/private-ip.ts]: I'd rather lowercase() here, but I think it's unnecessary as node normalizes it.

**Review by MartinKolarik — APPROVED** [review]
